CC ?= gcc
CXX ?= g++
CFLAGS ?=

CJSON_SRC=lib/libreddit/lib/cJSON/cJSON.c lib/libreddit/lib/cJSON/cJSON_Utils.c

B64_SRC=lib/libreddit/lib/librequest/lib/b64.c/buffer.c lib/libreddit/lib/librequest/lib/b64.c/decode.c lib/libreddit/lib/librequest/lib/b64.c/encode.c

REQ_SRC=lib/libreddit/lib/librequest/src/main/res.c lib/libreddit/lib/librequest/src/main/header.c lib/libreddit/lib/librequest/src/main/request_generic.c
REDDIT_SRC=lib/libreddit/src/Reddit.c lib/libreddit/src/Post.c lib/libreddit/src/List.c lib/libreddit/src/Subreddit.c lib/libreddit/src/Comment.c

INCLUDES=-Ilib/libreddit/lib/librequest/include -Ilib/libreddit/include -Ilib/libreddit/lib/cJSON -Ilib/libreddit/lib/librequest/lib/b64.c/

WXREDDIT_SRC=src/main/MainApp.cpp src/main/MainFrame.cpp src/main/MainFrameCust.cpp src/main/Table.cpp src/main/Util.cpp src/main/main.cpp src/main/specific/Win32.cpp

libreddit.dll:
	${CC} -fPIC -shared -o libreddit.dll ${INCLUDES} ${CJSON_SRC} ${B64_SRC} ${REQ_SRC} lib/libreddit/lib/librequest/src/main/backends/darwin/request.m ${REDDIT_SRC} -framework Foundation
 
librequest.dll:
	${CC} -fPIC -shared -o librequest.dll ${INCLUDES} ${CJSON_SRC} ${B64_SRC} ${REQ_SRC} lib/librequest/src/main/backends/curl/request.c ${REDDIT_SRC} `pkg-config --libs --cflags libcurl` -lwininet

WxReddit:
	mkdir -p buildwin
	${CC} -o WxReddit.exe ${INCLUDES} ${WXREDDIT_SRC} ${CJSON_SRC} ${B64_SRC} ${REQ_SRC} lib/libreddit/lib/librequest/src/main/backends/curl/request.c ${REDDIT_SRC} `wx-config --libs --cflags` -lstdc++ -lcurl -DNO_EXPORT
	mv WxReddit.exe buildwin/
	cp /usr/i686-w64-mingw32/sys-root/mingw/bin/*.dll buildwin/
	cp res/WxReddit.exe.manifest buildwin/
	curl 'https://curl.se/ca/cacert-2022-04-26.pem' --output 'buildwin/curl-ca-bundle.crt'

clean:
	rm -rf *.dylib *.so
